### ISSUE TITLE
Add .vsix file to the released files

### ISSUE THREAD

**Issue by themr0c** [testthedocs/vscode-vale#15]
As the new VSCode Marketplace license formally prohibits the usage of direct links to the Marketplace for tools other than the official VSCode binary build, other tools using the VSCode extensions need another source to fetch the  `.vsix` files.

One option is to add this file in the GitHub release, like it has been done for the asciidoctor extension https://github.com/asciidoctor/asciidoctor-vscode/issues/221.

Would you consider adding the `.vsix` file as part of the next releases?

**Comment by ChrisChinchilla** [comment]
@themr0c I don't really understand your statement, but I am perfectly happy to add the .vsix if that's useful for people.

**Comment by nickboldt** [comment]
Basically you're not allowed to use vscode plugins from the vscode marketplace in any tool/product other than vscode. 

@themr0c is asking that you publish your .vsix file as part of your releases (ie. on https://github.com/testthedocs/vscode-vale/releases/tag/0.9.0 you only have sources, not binaries), so that **ANY products** that want to use/promote your work can do so without violating MS's new license terms. 

This would allow your work to be used in Che 7 and CodeReady Workspaces, as well as other Theia-based IDEs that use vscode plugins.

**Comment by ChrisChinchilla** [comment]
@nickboldt and @themr0c first, I thought I had already pushed the file to repo, but I had forgotten. I also added to the release (https://github.com/testthedocs/vscode-vale/releases/tag/0.9.0), but as I think I have to do that manually, I may forget to add the vsix to each release.

**Comment by ChrisChinchilla** [comment]
And - https://github.com/testthedocs/vscode-vale/blob/master/vale-0.9.0.vsix which will update of course

**Comment by themr0c** [comment]
Thank you!
