### ISSUE TITLE
Plugin does not pull in the config file automatically

### ISSUE THREAD

**Issue by Ravlen** [testthedocs/vscode-vale#25]
I can only get the plugin to work by manually setting the config file. I'd like to be able to leave it blank, and have it look up the directory tree until it finds a config file, and use that one. That way I can use a different config file for each repo I use Vale with (5 repos so far, each with some minor differences in the styles we've defined).

It could be that this is possible, but didn't work when I tried it (as discussed externally with @ChrisChinchilla)

**Comment by jdkato** [comment]
This has been fixed in https://github.com/errata-ai/vale-vscode, which @ChrisChinchilla and I have been working on together.

He might have more to say about the future of this package, but my understanding is that we'd like to move to that one once it has been thoroughly tested (the Vale CLI support is still fairly new over there).

**Comment by ChrisChinchilla** [comment]
Yes I mentioned this to @Ravlen in our testing interview, feel free to replace this extension with the "new" one and see if it solves your issues, but I wanted to run with it myself for a week or so before unleashing something that may not work so well in production yet… It probably does, but you never know.
